---
- name: show remote environment
  shell: env

- name: "copy backend build"
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/udapeople_backend
    recursive: true

- name: "copy backend dependencies"
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/udapeople_backend
    recursive: true

- name: "start server"
  shell: |
    pm2 start /home/ubuntu/udapeople_backend/dist/main.js -f
